name: PowerShell VM Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Az module
      shell: pwsh
      run: Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force

    - name: Run PowerShell Script
      shell: pwsh
      run: ./create-vm.ps1
